# Generated by Django 2.2.19 on 2021-03-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votazioni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatidonna',
            name='nome_e_cognome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='candidatiuomo',
            name='nome_e_cognome',
            field=models.CharField(max_length=255),
        ),
    ]
