# Generated by Django 2.2.19 on 2021-03-22 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votazioni', '0002_auto_20210322_2242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidatidonna',
            options={'verbose_name': 'Candidato donna', 'verbose_name_plural': 'Candidate donna'},
        ),
        migrations.AlterModelOptions(
            name='candidatiuomo',
            options={'verbose_name': 'Candidato uomo', 'verbose_name_plural': 'Candidati uomo'},
        ),
    ]
